@startuml Power Manager


class ControlInterface{
    + getConsumption(): void
    + consumedGridPower(): void
    + generatedRenewablePower(): void

    + chargedBatteryPower(): void
    + consumedBatteryPower(): void
    + batteryPercentage(): void

    /'+ heatingControl(): void
    + applianceControl(): void'/
}

class PowerGridEnergy{
    
}


interface RenewableEnergy{

}

class SolarPower{

}

class WindPower{

}


class Battery{
    - percentage: int

    + charge(): void
    + devertExcessPower(): void
}

interface PowerSource{
    - consumedPower: int
}

interface PowerConsumer{
    - consumption: double
}

class Inverter{
    + flowControl(): void
    + report(): void
}

class CloudAPI{

}

interface Household{
  - isON: boolean
}

class ImmersionWaterHeater{
}

interface Heating{
}

interface Appliance{
}

class ElectricKettle{
}

class ElectricHeater{

}



interface ReportGenerator{
    + generateReport(): Report
}

class EcoReport {
    + generateReport(): Report
}

class OverallConsumptionReport{
    + generateReport(): Report
}

class NonEcoReport {
    + generateReport(): Report
}

class UsageReport{
    + generateReport(): Report
}


class Controller{
    + turnOn(): void
    + turnOff(): void
} 

/' class HeatingController{

}

class ImmersionWaterHeaterController{

}

class ApplianceController{

} '/
 


ControlInterface "1"--"1" Inverter

Battery <|-- RenewableEnergy
PowerSource <|.. PowerGridEnergy

RenewableEnergy <|.. SolarPower
RenewableEnergy <|.. WindPower

Appliance <|.. ElectricKettle

PowerSource <|.. Battery

PowerConsumer <|.. Battery


Inverter "1"--"1" CloudAPI
Inverter "1"--"1..*" PowerSource
Inverter "1"--"1..*" PowerConsumer


ReportGenerator <|.. EcoReport
ReportGenerator <|.. NonEcoReport
ReportGenerator <|.. OverallConsumptionReport
ReportGenerator <|.. UsageReport

Controller "1"--"1..*" Heating
Controller "1"--"1..*" Appliance


ControlInterface "1"--"1" ReportGenerator

Household <|.. Heating
Household <|.. Appliance

Heating <|.. ImmersionWaterHeater
Heating <|.. ElectricHeater


PowerConsumer <|.. Household

@enduml