@startuml Power Manager

class System{
    + divertEnergy(): void
}

class ControlInterface{
    + consumedPower(): void
    + consumedGridPower(): void
    + generatedRenewablePower(): void
    + chargedBatteryPower(): void
    + consumedBatteryPower(): void 
    + batteryPercentage(): void
    + consumedHeatingPower(): void
    + controlAppliance(): void
    + controlHeating(): void
    + heatingEnergyConsumption(): void
    + viewReport(): void
}


interface RenewableEnergy{

}

class SolarPower{

}

class WindPower{

}


class Battery{
    - percentaeg: int

    + charge(): void
    + isFullyCharged(): boolean
}

class PowerSource(){

}

class PowerConsumer(){

}

class BiDirectionalInverter{
    + flowControl(): void
    + report(): void
}

class CloudAPI{

}

class ImmersionWaterHeater{

}

class Heating{
    - isON: boolean
}

class Appliance{
    - isON: boolean
}

class ElectricKettle{

}



interface ReportGenerator{
    + generateReport(): Report
}

class EcoReport {
    + generateReport(): Report
}

class OverallConsumptionReport{
    + generateReport(): Report
}

class NonEcoReport {
    + generateReport(): Report
}

class UsageReport{
    + generateReport(): Report
}
 


System -- ControlInterface
System -- Battery
System -- BiDirectionalInverter
Battery <|-- RenewableEnergy

RenewableEnergy <|.. SolarPower
RenewableEnergy <|.. WindPower

BiDirectionalInverter -- CloudAPI
System -r- Heating
System -l- ImmersionWaterHeater
Appliance -- System
ElectricKettle -- Appliance :include

ReportGenerator <|.. EcoReport
ReportGenerator <|.. NonEcoReport
ReportGenerator <|.. OverallConsumptionReport
ReportGenerator <|.. UsageReport


@enduml