@startuml Power Manager


class PowerGrid{
    
}


interface RenewableEnergy{
    + chargeImmersionHeater(): void
}

class SolarPower{

}

class WindPower{

}


class Battery{
    - percentage: int
    - enteringPower: double
    - leavingPower: double
    - isFull: bool

    + charge(): void
}

interface PowerSource{
    - consumedPower: int
}

interface PowerConsumer{
    - consumption: double
}

class Inverter{
    + flowControl(): void
    + report(): void
}

class CloudAPI{

}

interface Household{
  - isON: boolean
}

class ImmersionHeater{
}

interface Heating{
}

interface Appliance{
}

class ElectricKettle{
}

class ElectricHeater{

}



class ReportGenerator{
    + generateReport(): Report
}



class Controller{
    + turnOn(): void
    + turnOff(): void
} 



Battery <-- RenewableEnergy
PowerSource <|.. PowerGrid

RenewableEnergy <|.. SolarPower
RenewableEnergy <|.. WindPower

Appliance <|.. ElectricKettle

PowerSource <|.. Battery

PowerConsumer <|.. Battery


Inverter "1"--"1" CloudAPI
Inverter "1"--"1..*" PowerSource
Inverter "1"--"1..*" PowerConsumer


ReportGenerator <-- RenewableEnergy
ReportGenerator <-- PowerGrid
ReportGenerator <-- PowerConsumer

Controller <-- Household


Household <|-- Heating
Household <|-- Appliance

Heating <|.. ImmersionHeater
Heating <|.. ElectricHeater

RenewableEnergy "1"--"1" ImmersionHeater


PowerConsumer <|-- Household

@enduml